tari-project/tari-launchpad

README.md
backend/src/rest/mod.rs
backend/src/rest/quay_io.rs
gui-react/.gitignore

Description
---
Just getting the party kicked off
---
Get CI green for next set of PR's
---
CI hopefully

chore(ci): minor fixes for green

---

backend/src/docker/settings.rs
docker_rig/start_tari_app.sh

Description
---
Directory storage is landing in a generic APP_NAME folder and should be in each independent app folder.
---
Looks wrong, maybe now is better.
---
It hasn't. Building the images locally is proving...  Difficult. So I shall let CI do it for me.

fix: use appropriate dirs for storage

---

gui-react/src/locales/onboarding.ts

Description
---
Changed the spelling of "awsome" to "awesome"
---
Picked up a spelling mistake in the onboarding flow
---
N/A

fix: typo in onboarding flow

---

backend/src/commands/service.rs
gui-react/src/store/settings/types.ts

Description
---
Get the Grafana, Loki, and Promtail containers running again.
---
They ain't running now.
---
Manually
Closes #110

fix: ensure config for logging is present

---

gui-react/src/containers/SettingsContainer/BaseNodeSettings/BaseNodeSettings.tsx

Description
---
Activates "Save changes" button if the "Root path" changed.
---
Fixes #132 
---
Manually

fix: activate Save button if path is changed

---

.github/workflows/release.yml
gui-react/src/containers/Onboarding/index.tsx

Description
---
Add release workflow
---
So I don't have to do it manually
---
Watching it run now

chore: add the suggested Tauri release flow

---

gui-react/src/config/onboardingMessagesConfig.tsx

Description
---
Made the wait time on the intro messages a bit slower, so it's easier to read
---
Issue #106 
---
Manually

fix: made intro messages scroll slower

---

gui-react/src/containers/SettingsContainer/BaseNodeSettings/BaseNodeSettings.tsx

Description
---
Fix CLI warnings
---
Get CI green again
---
in CI

fix: ci errors

---

gui-react/public/index.html
gui-react/src/layouts/MainLayout/index.tsx
gui-react/src/styles/App.css

Description
---
Added rounded corners to the Expert View overlay and deleted a default white background style.
---
When expert view was toggled, the corners were square and overlapped the rounded window.
There was also a default white background on the body element, causing the white block in the corners when in dark mode.
Fixes issue #130 
---
Manually

fix: rounded corners

---

.github/workflows/coverage.yml

Description
---
Remove call to create existing directory
---
See if it fixes the coverage workflow
---
It has not

chore: attempt coverage workflow fix

---

gui-react/src/components/Onboarding/OnboardingMessages/IntroMessages.tsx
gui-react/src/layouts/MainLayout/index.tsx
gui-react/src/store/settings/types.ts

Description
---
There were various calls to setExpertSwitchDisabled() that were overlapping each other. I removed the unnecessary calls.
---
In the intro, once you get to the blockchain sync message, the expert view button is disabled.
The button also flashes on and off during the intro sequence.
Fixes issue #111 
---
Manually

fix: expert view button in intro

---

backend/src/commands/cleanup.rs
backend/src/commands/pull_images.rs
backend/src/docker/cleanup.rs
backend/src/docker/mod.rs
backend/src/docker/models.rs
backend/src/docker/workspace.rs
backend/src/main.rs
gui-react/src/store/settings/thunks.ts

Description
---
The full reset implementation. It allows a user to clean the cache, tables and containers (images).
---
Allows users to return the app to the initial state.
---
Manually

fix: reset cache of the app

---

backend/assets/config.toml

Description
---
Corrects the incorrect pruning horizon.
---
I did it wrong.
---
Nah, assumptions it'll work correctly are being made.

fix: change pruning horizon to the appropriate 10080

---

gui-react/src/containers/BaseNodeContainer/BaseNode.tsx
gui-react/src/locales/baseNode.ts

Description
---
Added frontend for block info on base node page.
Variables are currently hardcoded - Denis / Brian to pull data from backend.
---
Issue #149 
---
Manually

feat: add block info to base node page

---

gui-react/src/components/CopyBox/index.tsx
gui-react/src/components/CopyBox/styles.ts
gui-react/src/containers/WalletContainer/TariWallet/TariId.tsx
gui-react/src/styles/Icons/Copy.tsx

Description
---
Added horizontal scrolling for wallet ids
---
Issue #75 
---
Manually

feat: add horizontal scrolling to wallet id

---

Cargo.lock
backend/Cargo.toml
backend/src/api/base_node_api.rs
backend/src/api/mod.rs
backend/src/api/wallet_api.rs
backend/src/grpc/error.rs
backend/src/main.rs
libs/protocol/src/config.rs
libs/protocol/src/container.rs
libs/protocol/src/launchpad.rs
libs/sdm-launchpad/src/api.rs
libs/sdm-launchpad/src/lib.rs
libs/sdm-launchpad/src/resources/config.rs
libs/sdm-launchpad/src/resources/images/l1_tor.rs
libs/sdm-launchpad/src/resources/images/l2_base_node.rs
libs/sdm-launchpad/src/resources/images/l2_wallet.rs
libs/sdm-launchpad/src/tauri.rs
libs/sdm/src/image/checker.rs
libs/sdm/src/image/task/docker.rs
libs/sdm/src/image/task/events.rs
libs/sdm/src/image/task/mod.rs
libs/sdm/src/image/task/update.rs

Description
---
This PR integrates adds GRPC task that tracks a stream to the base_node or a wallet.
---
The app tried to open GRPC stream on start when they are not available. In order not to miss any message we should scan GRPC and connect to it as soon as it's available.
---
Manually, CI

feat: gRPC workers

---

backend/assets/config.toml

Description
---
Update the seed list.
---
Couldn't sync the chain with old seed list.
---
Manually

chore: update seed list for esme

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
cli/src/dashboard.rs
cli/src/main.rs
libs/protocol/src/config.rs
libs/protocol/src/launchpad.rs
libs/protocol/src/lib.rs
libs/protocol/src/session.rs
libs/sdm-launchpad/src/api.rs
libs/sdm-launchpad/src/bus.rs
libs/sdm-launchpad/src/resources/images/l2_base_node.rs
libs/sdm-launchpad/src/wallet_grpc.rs

Description
---
Adds a CLI launchpad version.
---
Adds a reference implementation that uses the `sdm` features.
---
Manually

feat: add cli tool

---

backend/src/api/base_node_api.rs
backend/src/api/wallet_api.rs
backend/src/main.rs

Description
---
Reverts methods for subscribing to grpc streams.
---
The PR #186 broke the welcome bot. This PR reverts changes.
---
Checked in fc150c4 that has the original implementation of methods to subscribe to grpc from the UI

fix: revert method for subscribing to grpc streams

---

Cargo.lock
backend/Cargo.toml
backend/src/main.rs
libs/protocol/src/lib.rs
libs/sdm-launchpad/src/lib.rs
libs/sdm-launchpad/src/tauri.rs

Description
---
This PR activates sdm bus on Tauri setup.
---
Integrate the sdm state with the UI.
---
Manually

fix: activate the bus on tauri setup

---

gui-react/src/components/CopyBox/index.tsx
gui-react/src/components/CopyBox/styles.ts
gui-react/src/containers/SettingsContainer/WalletSettings/WalletSettings.tsx
gui-react/src/containers/WalletContainer/TariWallet/TariId.tsx

Description
---
Css fixes to the wallet id displays
---
There were some small inconsistencies between the way the id displays in settings and in the wallet
---
Manually

fix: small edit to id display

---

libs/README.md

Description
---
The description for the sdm crate and changes required for the UI.
---
---

feat: add a description for sdm

---

gui-react/src/styles/App.css

Description
---
Added a colour style to the main body element
---
When an error appears, the background is transparent
---
Manually

fix: background on error page

---

Cargo.lock
libs/protocol/Cargo.toml
libs/protocol/src/container.rs
libs/sdm-launchpad/src/resources/images/l2_wallet.rs
libs/sdm/Cargo.toml
libs/sdm/src/image/checker.rs
libs/sdm/src/image/task/docker.rs
libs/sdm/src/image/task/events.rs
libs/sdm/src/task.rs

Description
---
This PR fixes a wallet image and forwards stats of containers.
---
To get stats from containers.
---
CI, Manually

fix: wallet image configuration + forward stats

---

docker_rig/monerod.Dockerfile
docker_rig/tor.Dockerfile
docker_rig/xmrig.Dockerfile

Description
Update monero and xmrig to current release
---
Built locally for both x86-64 and arm64.

feat(ci): 3rdparty images version bump

---

libs/protocol/src/container.rs
libs/sdm-launchpad/tests/common.rs
libs/sdm-launchpad/tests/test_launch.rs
libs/sdm-launchpad/tests/test_mining.rs
libs/sdm/src/image/task/docker.rs

Description
---
Adds integration tests to check containers launch and mining.
---
Automate testing of the state and changes.
---
Locally

fix: add integration tests

---

Cargo.lock
backend/Cargo.toml
cli/Cargo.toml
libs/protocol/Cargo.toml
libs/sdm-assets/Cargo.toml
libs/sdm-launchpad/Cargo.toml
libs/sdm/Cargo.toml
libs/sim-launchpad/Cargo.toml

Description
---
The PR upgrades compatible dependencies.
---
Keeping dependencies up to date.
The update is essential for upgrading the `tari` dependencies set.
---
CI

chore: upgrade dependencies (compatible)

---

Cargo.lock
cli/Cargo.toml
cli/src/component/expert/containers/mod.rs
cli/src/component/expert/mod.rs
cli/src/component/normal/base_node/mod.rs
cli/src/component/normal/mod.rs
cli/src/component/normal/wallet/container.rs
cli/src/component/normal/wallet/mod.rs
cli/src/component/widgets/labeled_input.rs
cli/src/state/focus.rs
libs/protocol/src/session.rs
libs/sdm-launchpad/src/resources/images/l2_wallet.rs

Description
---
The PR introduces containers rendering capabilities to the CLI interface.
Add a widget to activate or deactivate the wallet container.
---
Mirroring a feature already present in the Web UI prototype.
---
Manually, CI

feat: render containers list and stats

---

build_images.sh
docker_rig/tarilabs.Dockerfile
hosted-dual.env
tarisuite.json

Description
Changes to support minotari rename
Fix docker builds for minotari
Build locally

ci(fix): minotari rename

---

libs/protocol/src/settings.rs
libs/sdm-assets/assets/config.toml
libs/sdm-launchpad/src/resources/images/l2_base_node.rs

Description
---
Changes `esmeralda` to `stagenet`.
---
Preparing to use `mainnet`.
---
CI, Manually

feat: use the stagenet

---

cli/src/component/expert/logs/mod.rs
libs/protocol/src/session.rs
libs/sdm-launchpad/src/resources/images/l1_tor.rs
libs/sdm-launchpad/src/resources/images/l2_base_node.rs
libs/sdm-launchpad/src/resources/images/l2_wallet.rs
libs/sdm-launchpad/src/resources/images/l3_miner.rs
libs/sdm-launchpad/src/resources/images/l5_mmproxy.rs
libs/sdm-launchpad/src/resources/images/l5_monerod.rs
libs/sdm-launchpad/src/resources/images/l5_xmrig.rs
libs/sdm-launchpad/src/resources/images/l8_grafana.rs
libs/sdm-launchpad/src/resources/images/l8_loki.rs
libs/sdm-launchpad/src/resources/images/l8_promtail.rs

Description
---
Fixes wallet connection to a base node.
---
The wallet couldn't connect to the base node.
---
Manually

fix: wallet connection

---

cli/src/component/normal/wallet/balance.rs
cli/src/component/normal/wallet/mod.rs
libs/protocol/src/wallet.rs
libs/sdm-launchpad/src/wallet_grpc.rs

Description
---
Displays the wallet's balance and its unique identifier.
---
This is part of the development of a comprehensive user interface for the wallet.
---
Manually, CI

feat: render balance and id of the wallet

---

cli/src/component/expert/errors/mod.rs
cli/src/component/expert/mod.rs
libs/protocol/src/container.rs
libs/protocol/src/errors.rs
libs/protocol/src/launchpad.rs
libs/sdm-launchpad/src/bus.rs
libs/sdm/src/task.rs

Description
---
Introduces the **Errors** tab within the app.
---
This feature allows users to view errors associated with Docker operations.
For instance, it highlights issues such as occupied ports.
---
Manually, CI

feat: errors tracking

---

cli/src/component/elements.rs
cli/src/component/expert/mod.rs
cli/src/component/mod.rs
cli/src/component/normal/base_node/container.rs
cli/src/component/normal/base_node/mod.rs
cli/src/component/normal/containers/mod.rs
cli/src/component/normal/mining/merged_mining.rs
cli/src/component/normal/mining/mod.rs
cli/src/component/normal/mining/tari_mining.rs
cli/src/component/normal/mod.rs
cli/src/component/normal/wallet/balance.rs
cli/src/component/normal/wallet/container.rs
cli/src/component/normal/wallet/mod.rs
cli/src/component/normal/wallet/password.rs
cli/src/component/normal/wallet/send_funds.rs
cli/src/state/focus.rs
cli/src/state/mod.rs

Bring the design into a much more compact form, compressing the empty space and pulling a lot more info onto a single screen

feat: compact tui

---

libs/protocol/src/tari_format.rs

Description
---
Missed a few failing tests somehow

fix: formatting tests

---

libs/sdm/README.md

Include original rationale for the SDM (Software-defined mining) crate.

docs: add sdm readme

---

cli/src/component/normal/wallet/balance.rs

Description
---
Adds a short note telling users how to access the wallet. This can be deprecated once sweeping is added.

feat: help note

---

.github/workflows/pr_title.yml

Description
Update pr_title workflow.
Prevent code injection.

ci(fix): prevent code injection

---

.github/dependabot.yml
.github/workflows/audit.yml
.github/workflows/launchpad_v2.yml
.github/workflows/release.yml
.github/workflows/reusable-ci-jobs.yml
.github/workflows/reusable-licenses.yml
.github/workflows/reusable-tests.yml
.license.ignore
scripts/install_ubuntu_dependencies.sh

Description
Update and modernise all the CI workflows. Including formatting, replacement of older/unmaintained workflow actions. 
Cleaner and better CI
Built in local fork.

ci(fix): modernise - dependadbot/actions/formatting

---

.github/workflows/audit.yml

Description
Correct the audit workflow action

ci(fix): correct audit action

---

README.md
cli/src/component/normal/base_node.rs
cli/src/component/settings/wallet.rs

Description
---
Improve readme
remove wallet id setting as its unused and cant be set. Its derived from the private key, so you cant set the public key and work that way around. 
Remove base node id, as its not used by the base node only the wallets. 
---
---

feat: improvements

---

.license.ignore
docker_rig/tarilabs.Dockerfile

Description
Improve the docker image build process, mostly for cross-compile.
Cleans up the docker file and move the cross-compile parts into a script.
Builds locally

ci(fix): improve the docker build for cross-compile

---

.github/workflows/build_cli.json
.github/workflows/build_cli.yml
scripts/cli/install_ubuntu_dependencies-arm64.sh
scripts/cli/install_ubuntu_dependencies.sh

Description
Adds a build matrix for tari-lp-cli
Easy access to binaries for tari-lp-cli - Currently builds linux-x86, macos-x86, windows-x86
Built in local fork

chore(ci): add ci for tari-lp-cli

---

docker_rig/tarilabs.Dockerfile

Description
Fix tari_suite docker image builds
New dependency in tari repo update
Built locally successfully

chore(fix): ci - docker builds - hash_domains

---

.github/workflows/build_cli.yml

Description
Add checksum, name binary as needed and upload to s3.
---
Built and run in local fork.

chore(fix): ci - add checksum and s3 upload

---

.github/workflows/build_cli.yml

Description
Add tari network selection from repo settings file.
Add version from Cargo for release
Add protobuf for newer release 
Improved assets
Built in local fork

chore(fix): ci - add version and network from settings file

---

.github/workflows/build_cli.yml

Description
Add OSX codesign and include all assets for uploading
Improve UX
Not tested

chore(fix): ci - add osx codesign and include all assets for uploading

---

.github/workflows/build_cli.yml

Description
Fix typo in extra macOS preparation

chore(fix): ci - fix typo for osx codesign

---

cli/src/component/normal/mining/mining_panel.rs
cli/src/component/normal/mod.rs
cli/src/state/focus.rs
libs/sdm-assets/assets/settings.toml
libs/sdm-launchpad/src/resources/images/l5_mmproxy.rs

Description
---
- Make it so the wallet addresses can be input on the main screen without navigating to settings.
- Fix MMProxy dependency chain
---
More in yo face
---
Manually

feat: wallet addresses on main screen

---

cli/src/component/main_view.rs
cli/src/component/normal/mining/mining_panel.rs
cli/src/component/normal/mod.rs
cli/src/component/settings/mining.rs
cli/src/component/widgets/labeled_input.rs
libs/protocol/src/settings.rs
libs/sdm-assets/assets/config.toml
libs/sdm-assets/assets/settings.toml
libs/sdm-assets/src/configurator.rs
libs/sdm-launchpad/src/bus.rs

Description
---
A few small persistence fixes. Trigger events to ensure state is updated for setting rendered on different screens.
---
---
manually

feat: settings persistence

---

Cargo.lock
backend/Cargo.toml
cli/Cargo.toml

chore: version bump to 1.4.0

---

Cargo.lock
backend/Cargo.toml
cli/Cargo.toml

Description
---
version bump to 1.5.0
---
---

chore: version bump to 1.5.0

---

cli/src/dashboard.rs

Provides a handy url to download docker based on your architecture
Description
---
---
---

feat: provide docker url

---

cli/src/component/expert/logs/mod.rs
cli/src/component/widgets/labeled_input.rs

Description
---
Improved screen real estate usage.
---
Some fields were allocated too little space to display their content optimally.
---
System-level testing

feat: improve screen real estate usage

---

cli/src/component/normal/legend_widget.rs
cli/src/component/normal/mining/helpers.rs
cli/src/component/normal/mining/mining_panel.rs
libs/protocol/src/container.rs
libs/sdm/src/task.rs

Description
---
Fixes merge mining Ctrl-M issue by replacing it with Ctrl-X.
Add statuses for waiting to start, and shutdown.
---
Mo statutes for people to understand what's happening.
---
Manually

feat: shutdown and waiting statuses

---

backend/Cargo.toml
cli/Cargo.toml

Description
---
version bump for release.
---
Moving up, moving on.
---
#yolo

chore: version bump to 1.7.0

---

Cargo.lock

chore: missed the lock

---

cli/src/component/main_view.rs
cli/src/component/normal/legend_widget.rs
cli/src/component/normal/mining/mining_panel.rs
cli/src/component/normal/mod.rs
cli/src/component/settings/base_node.rs
cli/src/component/settings/mining.rs
cli/src/component/widgets/labeled_input.rs
cli/src/component/widgets/qr_code.rs
cli/src/dashboard.rs
cli/src/events.rs
libs/protocol/src/lib.rs
libs/protocol/src/node.rs
libs/protocol/src/settings.rs
libs/sdm-assets/assets/log4rs-cli.yml
libs/sdm-launchpad/src/resources/config.rs
libs/sdm-launchpad/src/resources/images/l2_base_node.rs
libs/sdm-launchpad/src/resources/images/l3_miner.rs
libs/sdm-launchpad/src/resources/images/l5_mmproxy.rs
libs/sdm/src/image/task/docker.rs
ui/backend/src/main.rs

Description
---
- Fixed the Windows copy/paste issue where a `v` will always be added to the paste buffer when using `Ctrl-v` to paste.
- Changed the wallet address labelled input to always display the wallet address using the emoji ID string.
---
See above.
---
System-level testing on Windows and Ubuntu Linux

feat: fix windows copy-paste issue

---

docker_rig/tarilabs.Dockerfile

Description
Add new TARI_TARGET_NETWORK env
Fix nextNet docker images

chore: dockerfile add TARI_TARGET_NETWORK env

---

Cargo.lock
backend/Cargo.toml
cli/Cargo.toml

Description
---
Version bump
---
Get the windows copy paste bug fixed
---
#yolo

chore: version bump 1.8.0

---

backend/assets/config.toml
libs/sdm-assets/assets/config.toml

Description
---
Fixes the config file to match the release of rc.8's config file

fix: update config file

---

Cargo.lock
backend/Cargo.toml
cli/Cargo.toml

Description
---
version bump to 1.9.0
---
onwards and upwards
---
#yolo

chore: version bump to 1.9.0

---

libs/protocol/src/settings.rs
libs/sdm-launchpad/src/resources/images/l5_mmproxy.rs
libs/sdm-launchpad/src/resources/images/l5_xmrig.rs
libs/sdm/src/image/task/mod.rs
libs/sdm/src/network/task/mod.rs
libs/sdm/src/task.rs
libs/sdm/src/volume/task/mod.rs

Description
---
fixes Clippy 
---
---

chore: fix clippy

---

backend/assets/config.toml
docker_rig/config.toml
libs/sdm-assets/assets/config.toml

Description
---
Removes config option that does not exit anymore. 
---
If this PR gets merged: #https://github.com/tari-project/tari/pull/6320
This will cause LP to break if this is not merged

feat: remove config option

---

.github/workflows/release.yml
ui/backend/Cargo.toml

Description
Update the CI build process
Provide supported platforms
Builds in local fork

ci(fix): gui build workflow

---

ui/frontend/src/App.tsx
ui/frontend/src/components/StyledComponents.ts
ui/frontend/src/containers/BaseNodeContainer/BaseNodeFooter.tsx
ui/frontend/src/containers/BaseNodeContainer/BaseNodeHelp/BaseNodeHelp.tsx
ui/frontend/src/containers/BaseNodeContainer/BaseNodeHelp/Messages.tsx
ui/frontend/src/containers/BaseNodeContainer/BaseNodeTab.tsx
ui/frontend/src/containers/BaseNodeContainer/BaseNodeWidget.tsx
ui/frontend/src/containers/BaseNodeContainer/styles.ts
ui/frontend/src/containers/Dashboard/DashboardContainer/MainTabs.tsx
ui/frontend/src/containers/DockerWarning/DockerWarning.tsx
ui/frontend/src/containers/MiningContainer/MiningBoxMerged/MergeMiningWidget.tsx
ui/frontend/src/containers/MiningContainer/MiningHelp/Messages.tsx
ui/frontend/src/containers/MiningContainer/MiningHelp/MiningHelp.tsx
ui/frontend/src/containers/MiningContainer/MiningTab.tsx
ui/frontend/src/containers/MiningContainer/components/Amount.tsx
ui/frontend/src/containers/MiningContainer/components/Timer.tsx
ui/frontend/src/containers/MiningContainer/styles.ts
ui/frontend/src/containers/SettingsContainer/SettingsDialog.tsx
ui/frontend/src/containers/TBotContainer/TBot.tsx
ui/frontend/src/containers/TBotContainer/styles.ts
ui/frontend/src/locales/baseNode.ts
ui/frontend/src/locales/cryptoMiningHelp.ts
ui/frontend/src/locales/mining.ts
ui/frontend/src/store/appStateStore.ts
ui/frontend/src/store/types.ts
ui/frontend/src/theme/MainLayout.tsx
ui/frontend/src/theme/MainLayoutBackup.tsx
ui/frontend/src/theme/styles.ts
ui/frontend/src/theme/tokens.ts

Description
---
Adds improvements to the taribot component and messages depending on the states of the miners / base node.
Fixed a bug that caused the settings dialog to rerender while mining is on.
Various other small ui improvements.
---
Taribot & ui improvements
---
Manually

feat: taribot and ui updates

---

.github/workflows/reusable-ci-jobs.yml
libs/sdm/src/image/task/mod.rs

Description
---
Fix failing ci jobs
---
---

fix(ci): failing ci jobs

---

ui/frontend/src/App.tsx

Description
---
* Clear CPU stats when container stopped
* Display 0 instead of NaN
* Refactor code
---
---

fix(containers): clear cpu when stopping container

---

ui/frontend/src/containers/SettingsContainer/BaseNodeSettings/BaseNodeSettings.tsx

Description
---
Remove qr code empty section
---
This section contains only subheading
---

chore(ui): remove qr code empty section

---

ui/frontend/src/containers/SettingsContainer/MergedMiningSettings/MergedMiningSettings.tsx
ui/frontend/src/containers/SettingsContainer/SettingsDialog.tsx
ui/frontend/src/containers/SettingsContainer/types.ts
ui/frontend/src/locales/mining.ts

Description
---
Remove randomx threads settings
---
they do not work
---
manually

chore(mining): remove randomx threads setting

---

build_images.sh
docker_rig/monerod.Dockerfile
docker_rig/tarilabs.Dockerfile
docker_rig/tor.Dockerfile
docker_rig/xmrig.Dockerfile
hosted-dual.env

Description
Fix docker tari arm64 builds
Fix version RegEx
Bump 3rd-party docker builds
Bring things to date and working
Builds local

ci(fix): docker image builds for arm64 and bump 3rd-party versions
