tari-project/tari-launchpad

Cargo.lock, backend/Cargo.toml
Description
---
A commit got pulled from `tauri-plugin-sql` causing our Cargo.lock to break. Upon removing the lock different dependencies upgraded and caused conflicts. This PR locks a `sqlx-core` a dep of `tauri-plugin-sql` to a version that will align with other deps, and not cause conflicts.
---
The project builds once again huzzah!
=> fix(Cargo.lock): fix sql plugin dependency issue

gui-react/src/config/app.ts
Description
---
The dismissal was only valid for 5 minutes before and was slowly driving me insane. Set it to 24 hours. No need to hassle someone multiple times daily.
---
Manually
=> fix: define a longer container update reminder

docker_rig/tor.Dockerfile
Description
---
Turn off the Tor container healthcheck.
Fixes #97 in the most simplistic manner.
---
When the healthcheck moved from state "Starting" to "Healthy" it caused launchpad to become confused and believe the container had shut off. It's the only container that uses a healthcheck so it's the only container that intermittantly thinks it's offline.
---
Rebuilt the tor container locally and tested.
=> fix: tor container thinking it's offline

docker_rig/tarilabs.Dockerfile, docker_rig/tor.Dockerfile
Description
Remove docker cache for runtime stage as multi-stage docker builds in GHA runs too fast and breaks
Simplify ARM64 builds by including ARM debs in all builder stages and do rust toolchain in ARM64 hardcoded section  
Fix tari docker builds via GHA  
Builds locally and in GH local fork with GHA
=> fix(build): update tari docker builds

gui-react/src/components/TBot/TBotPrompt/index.tsx
Description
---
The background colour on TBot that had previously been opened, will now switch from light to dark mode when expert mode is toggled.
---
If TBot is open while expert view is on, the background on the messages is in dark mode. If expert mode is then switched off, the background remains dark until a new message appears, which then turns the background back to light mode.
Issue #120 
---
Manually
=> fix: update tbot background when expert view is toggled

Cargo.lock, backend/Cargo.toml, backend/src/docker/models.rs, backend/src/docker/wrapper.rs
Description
---
The PR upgrades all dependencies (except tauri and tari).
---
To keep dependencies up to date and avoid potential security issues.
---
CI
=> chore: upgrade dependencies

docker_rig/tarilabs.Dockerfile
Description
---
A small fix to adjust the paths files are put in.
---
---
Manually building the base node container locally and initializing it.
=> fix(dockerfile): variable naming in the path

gui-react/src/components/TBot/TBotPrompt/index.tsx
Description
---
TBot container messages could not be dismissed by pressing "x".
There was an extra action specific to the docker images that needed to be dispatched when pressing on the x to remove them from the TBot message queue.
---
Fixes issue #112  
---
Manually
=> fix: dismiss container messages with x

backend/src/docker/mod.rs, backend/src/docker/settings.rs, backend/src/grpc/model.rs
Description
---
A simple update to the wallet settings command to use the local base node when starting up.
---
We start a base node but there's no setting pane or _easy_ way for a user to utilize the node they're running. This PR updates the start command so the wallet actually utilizes the local base node.
---
Manually
Closes #127
=> feat: use the local base node

gui-react/src/containers/Onboarding/index.tsx
Description
---
If a user skips the blockchain syncing then they cannot use the app. So lets remove the skip button and force the wait to sync.
---
No sync makes for a broken experience.
---
Manually
Closes #107
=> fix: remove the skip sync button

Cargo.lock, backend/Cargo.toml, backend/src/docker/settings.rs, backend/src/grpc/model.rs, gui-react/src/store/settings/thunks.ts
Description
---
Upgrade to tari libs 0.38.3
---
Emojiid had a breaking change we need to support
---
Manually. The id is a single emoji different and transactions between LP and the cli wallet worked.
=> chore: bump to 0.38.3 to support emojiid breaking change

backend/src/docker/models.rs, docker_rig/config.toml, gui-react/src/containers/BaseNodeContainer/constants.ts, gui-react/src/containers/BaseNodeContainer/types.ts, gui-react/src/store/baseNode/index.ts, gui-react/src/store/containers/thunks.test.ts
Description
---
Using the esme shorthand created a regression in the Aurora base node selector QR code. To avoid issues like this in the future remove all shorthand and only use the longform.
---
It caused a regression with Aurora, and now that I think of it might have been why windows directories we're being created wrong 🤔
---
Manually
Fixes: #137
=> fix: remove remaining esme shorthand

gui-react/src/containers/SettingsContainer/BaseNodeSettings/BaseNodeSettings.tsx
Description
---
Improves #136. Uses `onChange` to update `rootFolder` value
---
Using `onChange` fixes the following issues:
1. `setValue` call doesn't enable `Save settings` button
2. explicit set of the `shouldDirty` marks form as changed even if value was reverted back to the original value
---
Manually
=> fix: use onChange to update rootFolder field

gui-react/src/components/Modal/index.tsx
Description
---
Allow to move app's window by dragging a backdrop of a modal window.
---
A backdrop of a modal window overlaps the title bar and doesn't allow to move window when the modal (settings) is opened.
Fixes #128 
---
Manually
=> feat: move window using a backdrop of a modal window

gui-react/public/index.html
Description
---
Made the app draggable when the splash screen is loading
---
When the app first loads and the loading animation is playing, you are not able to move the window around on the desktop
---
Manually
=> fix: add draggable region to splash screen

backend/assets/config.toml
Description
---
Make the base node a pruned node by default
---
Keeping LP a bit smaller
Fixes: #167 
---
yolo
=> feat: set prune horizon as default for base node

docker_rig/tarilabs.Dockerfile
Description
---
Moves the dockerfile entry to shell form so `$APP_NAME` might actually substitute to the correct path.
---
Still getting the `$APP_NAME` directory
---
It hasn't
=> chore: docker entry shell form

gui-react/src/components/DockerImagesList/index.tsx, gui-react/src/components/DockerImagesList/styles.ts, gui-react/src/containers/SettingsContainer/DockerSettings/DockerSettings.tsx, gui-react/src/locales/docker.ts
Description
---
Added a pull all button to the docker settings page.
Also fixed a couple of alignment and font size issues on the same page.
---
Previously, if there were many new images available, the user would have to click on each one separately to download. This allows for a single click to download all available images.
Issue #146 
---
Manually
=> feat: add pull all button to docker settings

.github/workflows/release.yml, backend/package.json, backend/tauri.conf.json, libs/sdm-launchpad/Cargo.toml
Description
PoC that we can do Apple M1 & Apple Universal DMG creation.
```tauri-apps/tauri-action``` &  ```yarn run tauri build``` seem to be aimed for release builds, which needs to bee worked around for cross-compiling.  
For testing, have artifacts for download and testing.  
Might be worth adding Windows builds and support Ubuntu ARM64 build. Need to update the release to include checksums, signing keys and extra packages to releases page. 
---
---
=> fix(ci): update GHA to include draft release and checksums

cli/src/dashboard.rs, libs/sdm-launchpad/src/resources/images/l2_base_node.rs, libs/sdm/src/image/checker.rs, libs/sdm/src/image/mod.rs, libs/sdm/src/image/task/docker.rs, libs/sdm/src/image/task/mod.rs, libs/sdm/src/image/task/update.rs
Description
---
Fixes progress updates blinking.
Also added methods to remove images and "Flag" column renamed to "Active".
---
`Active` status sometimes temporary changes to `Progress`.
Background workers of a task used not only checks a container its ready for using, but also maintains logs and stats streams. Since the worker is not terminated to keep that streams it's necessary to skip further `Progress` events from that workers.
---
Manually
=> fix: progress updates

docker_rig/tarilabs.Dockerfile
Description
Add integration_tests folder and bump rust docker base image to 1.67
fix docker builds
Built locally and in fork
=> ci(fix): fix docker builds

Cargo.lock, cli/src/component/expert/logs/mod.rs, cli/src/component/expert/mod.rs, cli/src/state/focus.rs, libs/protocol/Cargo.toml, libs/protocol/src/container.rs, libs/sdm/src/task.rs, libs/sim-launchpad/src/simulator.rs
Description
---
The PR introduces log rendering capabilities to the CLI interface.
---
Mirroring a feature already present in the Web UI prototype.
---
Manually, CI
=> feat: render logs

docker_rig/monerod.Dockerfile, docker_rig/tor.Dockerfile, docker_rig/xmrig.Dockerfile
Description
Bump 3rd party docker images
monero 0.18.2.0 -> 0.18.2.2
tor 0.4.7.13-r0 -> 0.4.7.13-r2
xmrig v6.19.1 -> v6.20.0
Update to latest releases.
Built locally on Apple M1 and Apple Intel and in local fork
=> ci(fix): bump 3rd party tools

cli/src/component/main_view.rs, cli/src/component/mod.rs, cli/src/component/termination.rs, cli/src/dashboard.rs, cli/src/state/focus.rs, cli/src/state/mod.rs, libs/protocol/src/container.rs
Description
---
Terminates containers on exit.
---
Сontainers remain running after the application is terminated, although they should be stopped.
---
Manually
=> feat: terminate containers on exit

libs/sdm-launchpad/src/resources/images/l2_wallet.rs
Description
---
Use the `stagenet` compatible image for the wallet.
---
To incorporate support for `stagenet`.
---
CI, Manually
=> feat: wallet stagenet

cli/src/component/expert/containers/mod.rs, cli/src/component/expert/logs/mod.rs
Description
---
Use percentage-based column width.
Render logs in chronological order.
---
The `ratatui` crate panics if a column width exceeds the remaining size.
---
Manually
=> fix: relative columns width

cli/src/component/normal/wallet/balance.rs, cli/src/component/normal/wallet/mod.rs, cli/src/dashboard.rs, libs/protocol/src/wallet.rs, libs/sdm-launchpad/src/resources/images/l3_miner.rs, libs/sdm-launchpad/src/resources/images/l5_mmproxy.rs, libs/sdm-launchpad/src/wallet_grpc.rs, libs/sim-launchpad/src/simulator.rs
Description
---
The images have changed to `stagenet`.
The wallet widget displays a complete breakdown of the balance, including pending and timelocked amounts.
---
Switch mining to the stagenet.
---
CI, Manually
=> fix: use stagenet images for mining

.github/workflows/release.yml, .github/workflows/reusable-ci-jobs.yml, .github/workflows/reusable-tests.yml, backend/src/docker/models.rs, cli/src/main.rs, libs/protocol/src/container.rs, libs/protocol/src/settings.rs, libs/sdm-assets/src/configurator.rs, libs/sdm-launchpad/src/bus.rs, libs/sdm-launchpad/src/resources/images/l2_base_node.rs, libs/sdm-launchpad/src/resources/images/l2_wallet.rs, libs/sdm-launchpad/src/resources/images/l3_miner.rs, libs/sdm-launchpad/src/resources/images/l5_mmproxy.rs, libs/sdm-launchpad/src/resources/images/mod.rs, libs/sdm/src/image/checker.rs, libs/sdm/src/image/mod.rs, libs/sdm/src/image/task/docker.rs, libs/sdm/src/image/task/events.rs, libs/sdm/src/image/task/mod.rs, libs/sdm/src/image/task/update.rs, libs/sdm/src/status.rs, libs/sdm/src/task.rs, libs/sim-launchpad/src/simulator.rs
As part of updating launchpad to use stage- and main-net, we need to
update the containers used, as well as bring configuratino up-to-date.
This PR is primarily focussed on updating the containers:
- use Github package repos instead of quay.io
- use stagenet instead of esme as default
- use ver 0.52 (this must change to stagenet-latest soon, but tags
aren't up yet)
docs:
- Parsing the code, adding some helpful docs as I go.
behaviour changes:
- Config files are *not* deleted on startup. This is important. Users should be able to tweak settings between launches and have them persist.
=> chore: update containers

backend/assets/config.toml, backend/src/docker/settings.rs, docker_rig/config.toml, libs/protocol/src/session.rs, libs/sdm-assets/assets/config.toml, libs/sdm-launchpad/src/resources/config.rs, libs/sdm-launchpad/src/resources/images/l1_tor.rs, libs/sdm-launchpad/src/resources/images/l2_base_node.rs, libs/sdm-launchpad/src/resources/images/l2_wallet.rs, libs/sdm-launchpad/src/resources/images/l3_miner.rs, libs/sdm-launchpad/src/resources/images/l5_mmproxy.rs, libs/sdm/src/image/task/update.rs, libs/sdm/src/task.rs
* Main fix was getting dependency management right.
There isn't _true_ automatic dep management. The `Session` struct has some boolean methods like `is_wallet_active()` that masks real dependencies. We should really have proper dependencies that don't rely on this hack.
* Fixing configuration in config.toml
Plenty of niggly settings (and many hours) to get this right. Sigh.
* Automatically configuring the custom base node based on its pubkey.
* Made node and wallet interactive so that `docker attach` works. This made debugging waaaaay easier.
Added some other logs which could come out, or become trace in future.
=> fix: get sha3 mining working

.github/workflows/reusable-ci-jobs.yml, .github/workflows/reusable-licenses.yml, .github/workflows/reusable-tests.yml
Some actions were using checkout@v2, which could possibly be why some workflows are failing due to conflicting permissions when installing Node
Description
---
---
---
=> chore: update checkout github action

.github/workflows/launchpad_v2.yml
No need to run on push when we're already running on pull requests
=> chore: deduplicate ci tests

cli/src/component/normal/wallet/balance.rs, libs/protocol/src/lib.rs, libs/protocol/src/tari_format.rs, libs/protocol/src/wallet.rs, libs/sdm-launchpad/src/wallet_grpc.rs, libs/sdm-launchpad/tests/test_mining.rs, libs/sim-launchpad/src/simulator.rs
Adds a little newtype, TariFormat that formats the balance values in a human-friendly way.
De- and Serialization is auto-unwrapped back to a u64 (muT)
Balances now looks like:
```
Available                                          974,845.997 T
Incoming                                           0 μT
Outgoing                                           0 μT
Timelocked                                         970,590.372 T
```
rather than:
```
Available                                          974845997000000
Incoming                                           0
Outgoing                                           0
Timelocked                                         970590372000
```
=> feat: improve balance formatting

.github/workflows/reusable-ci-jobs.yml
Node.js isn't required when running cargo clippy, and it often causes a deadlock / race for write permissions, failing the CI
=> fix: don't install node.js when doing cargo clippy

libs/protocol/src/tari_format.rs
Choice was between a bold Tau (𝛕) and Taurus (♉︎).
Ultimately I decided that tau looks a little better.
=> feat: select minotari symbol

libs/sdm-launchpad/src/bus.rs, libs/sdm-launchpad/src/resources/config.rs, libs/sdm-launchpad/src/resources/images/l2_base_node.rs, libs/sdm-launchpad/src/resources/images/l2_wallet.rs, libs/sdm-launchpad/src/resources/images/l3_miner.rs, libs/sdm-launchpad/src/resources/images/l5_mmproxy.rs
The tor control port password can be made ephemeral and random when the tor container is started. This password can be supplied to other containers so that they can access Tor.
This prevents actors that have access to the docker daemon from using the Tor control port -- assuming they're unable to `exec` or `attach` to any running container in order to access the environment.
=> feat: randomise tor control password

docker_rig/monerod.Dockerfile, docker_rig/tarilabs.Dockerfile, docker_rig/tor.Dockerfile, docker_rig/xmrig.Dockerfile
Description
Bump tor, xmrig and monerod releases. Add env override over base OS image, switching from bullseye to bookworm.
Use the latest code.
Built and pushed locally. No run tests yet.
=> ci(fix): bump 3rd party releases

cli/src/component/normal/containers/mod.rs, libs/protocol/src/container.rs, libs/sdm-assets/assets/config.toml, libs/sdm-launchpad/src/bus.rs
When docker is pulling containers -- if they don't exist, or during an upgrade, report the progress to the UI
This is exposed as a `Report::Delta` event.
=> feat: report container download status

libs/sdm-assets/assets/config.toml, libs/sdm-launchpad/src/resources/images/l2_base_node.rs
When starting from a completely clean build, the node doesn't create the id.
This requires running in non-interactive mode for now.
There's also a bug in the comms layer where the wallet's peer db must be deleted in order to get the wallet to connect internally to get the wallet to reconnect via TCP on next launch.
=> fix: startup issues

cli/src/component/normal/wallet/balance.rs, libs/protocol/src/settings.rs, libs/sdm-assets/assets/settings.toml, libs/sdm-launchpad/src/resources/images/l2_base_node.rs, libs/sdm-launchpad/src/resources/images/l2_wallet.rs
1. Wallet
* There are 2 extra settings in the wallet config. `clear_peer_db`, clears the peer database when configuring the wallet.
This should be true for at least the first run or until https://github.com/tari-project/tari/issues/5998 is fixed.
* `interactive` must be false for the first run, and can be set to true after that.
* We only display the instructions for attaching to the docker wallet instance if interactive is true, and the wallet is active.
2. Base node
Similarly to the wallet, there's an `interactive` setting for the base node now that must be false on the first run.
Note: A future PR should make these editable in the UI.
=> feat: fix startup bugs

cli/src/dashboard.rs
Description
---
Only propagate events on KeyRelease. 
---
Previously, all keyboard events, Down, Repeat, Up would trigger this event. We only need the first down or release. Doing actions on release might be a bit strange though, so I'll also try with KeyDown. I'm not super familiar with cross term though
---
Set your keyboard repeat rate to high to test the code before this change, then try it with this change
=> fix: don't spam key events

libs/sdm/src/image/task/docker.rs
Description
---
Use a simpler path conversion
---
Either this code is not being called or this way of doing it is fine, but the code runs on Windows fine with this change.
---
Tested running on Windows
=> fix: simpler path for windows

.license.ignore, Cargo.lock, backend/Cargo.toml, backend/assets/config.toml, cli/Cargo.toml, cli/src/component/normal/containers/mod.rs, cli/src/component/normal/wallet/mod.rs, cli/src/component/widgets/mod.rs, docker_rig/docker-compose.yml, libs/protocol/Cargo.toml, libs/protocol/src/container.rs, libs/protocol/src/node.rs, libs/protocol/src/settings.rs, libs/sdm-assets/assets/config.toml, libs/sdm-assets/assets/settings.toml, libs/sdm-launchpad/Cargo.toml, libs/sdm-launchpad/src/bus.rs, libs/sdm-launchpad/src/node_grpc.rs, libs/sdm-launchpad/src/resources/config.rs, libs/sdm-launchpad/src/resources/images/l2_base_node.rs, libs/sdm-launchpad/src/resources/images/l2_wallet.rs, libs/sdm-launchpad/src/resources/images/l3_miner.rs, libs/sdm-launchpad/src/resources/images/l5_mmproxy.rs, libs/sdm-launchpad/src/resources/images/sync_progress.rs, libs/sdm-launchpad/src/wallet_grpc.rs, libs/sdm/src/image/checker.rs, libs/sdm/src/image/task/events.rs, libs/sdm/src/image/task/mod.rs, rust-toolchain.toml, ui/frontend/src/widget/mod.rs
Description
---
This updates all the Tari libraries in use, and the containers that get fetched.
---
---
Manually on MacOS. 
Tor and the Base node connect and sync without issue on the nextnet network.
~It hasn't~
~LaunchPad does not function on my laptop. We don't know why yet.~
=> feat!: upgrade launchpad to tari 1.0.0-rc.2

Cargo.lock, backend/Cargo.toml, cli/Cargo.toml
Description
---
The version with no wallet.
=> chore: version bump to 1.3.0

.github/workflows/build_cli.json
Description
Add Apple arm64 (M1) build using the GitHub runner macos-14, which are M1 hardware, no need to cross-compile
Add Apple arm64 assets
Built in local fork
=> chore(ci): add apple arm64 build using macos-14 runner

Cargo.lock, cli/Cargo.toml, cli/src/component/main_view.rs, cli/src/component/mod.rs, cli/src/component/normal/mining/helpers.rs, cli/src/component/normal/mining/mining_panel.rs, cli/src/component/widgets/docker_detect.rs, cli/src/component/widgets/labeled_input.rs, cli/src/component/widgets/mod.rs, cli/src/component/widgets/popup.rs, cli/src/dashboard.rs, libs/protocol/src/settings.rs, libs/sdm-launchpad/src/lib.rs, libs/sdm-launchpad/src/resources/images/l5_mmproxy.rs
Description
---
Added a pop-up message for Docker if it is not running when the application starts and then exits.
---
The application remains unresponsive if Docker is not running when started.
---
System-level test
=> feat: add pop-up for docker

libs/sdm-assets/assets/settings.toml
Description
---
Missed updating these monero settings in the last PR.
---
Set to the mainnet community wallet.
---
manually
=> fix: commit missing monero settings

cli/src/component/normal/mining/mining_panel.rs, cli/src/component/widgets/labeled_input.rs, cli/src/component/widgets/mod.rs
Description
---
show a warning dialog if wallets aren't set and you try to mine.
---
prevents containers turning on for nothing
---
=> feat: show warning if wallets arent set

cli/src/component/widgets/docker_detect.rs, cli/src/dashboard.rs
Description
---
Enabled docker detect for WSL2 Ubuntu distributions.
---
The Docker version command (`docker --version`) behaves differently on WSL2 Ubuntu distributions compared to bare metal Ubuntu distributions when the `Use the WSL 2 based engine` setting is enabled, as it then uses the same Docker Desktop and engine for both Windows and Ubuntu.
---
System-level testing with Windows and WSL2 Ubuntu
=> feat: enable docker detect for wsl2

cli/src/component/normal/legend_widget.rs, cli/src/component/normal/mod.rs
Description
---
Adds a help / key commands pane to explain keyboard usage within the TUI.
---
Help users navigate the TUI
---
Manually
=> feat: add commands list help pane

cli/src/dashboard.rs
Description
---
This shuts down the app via a normal path and doesn't interfere with the terminal.
---
Less terminal mess.
---
Manually
=> fix: graceful no docker exit

libs/sdm-assets/assets/settings.toml
Description
---
Added a valid Monero mining address, obtained from https://www.getmonero.org/2021/06/24/general-fund-2020-2021-report.html
Closes #313
_**Note:** Solution pointed out by @CjS77_ 
---
The previous address was a donation address and not accepted by XMRig.
---
System-level testing on Ubuntu WSL.
=> feat: add a valid monero mining address

cli/src/component/main_view.rs, cli/src/dashboard.rs, cli/src/supervisor.rs, libs/sdm/src/image/task/docker.rs, libs/sdm/src/image/task/mod.rs, libs/sdm/src/image/task/update.rs
Description
---
- Added code to interpret all docker states with shutdown and act accordingly. This is to prevent Docker from going into undefined states with undefined behaviour.
- Improved shutdown, in general, to give time for docker containers to be shutdown properly.
- Improved shutdown when docker is closed manually.
---
All docker states were not interpreted and this caused docker containers to be left in undefined states when exiting.
---
System-level tests on Windows and Ubuntu-WSL
=> feat: interpret all docker states with shutdown

Cargo.lock, backend/Cargo.toml, cli/Cargo.toml
Description
---
version bump to v1.6.0
---
bumping version to v1.6.0
---
I looked at the number that was 1.5.0 and now it's 1.6.0.
=> chore: version bump to v1.6.0

cli/src/component/main_view.rs, libs/sdm/src/image/task/update.rs, libs/sdm/src/network/task/update.rs, libs/sdm/src/task.rs, libs/sdm/src/volume/task/update.rs
Description
---
- Removed the spinlock in the update loop in `tari-launchpad/libs/sdm/src/task.rs::update`. Events are being processed correctly and this is not required. 
- Added a bunch of trace logs to monitor the continued operation.
_**Note:** The spinlock was pointed out by @stringhandler_.
---
The spin lock unnecessarily kept the system busy during shutdown.
---
System-level testing:
- Start-then-stop-when-fully-active of all components works fine.
- Shutting down the application while all components are fully active works fine.
=> feat: remove spin lock

libs/protocol/src/container.rs, libs/sdm-launchpad/src/resources/images/l2_base_node.rs, libs/sdm-launchpad/src/resources/images/sync_progress.rs, libs/sdm/src/image/task/docker.rs
Description
---
- Show header sync status
- Cleanup anonymous volumes that some containers (tor 👀) leave lingering after shutdown
---
No lingering volumes and more accurate setup.
---
Manually
=> fix: header sync and lingering volumes

backend/Cargo.toml, backend/assets/config.toml, backend/assets/log4rs.yml, backend/tauri.conf.json, cli/src/component/mod.rs, cli/src/component/settings/mining.rs, cli/src/component/widgets/labeled_input.rs, cli/src/state/mod.rs, docker_rig/config.toml, docker_rig/docker-compose.yml, docker_rig/xmrig.Dockerfile, gui-react/package.json, libs/protocol/src/launchpad.rs, libs/protocol/src/lib.rs, libs/protocol/src/settings.rs, libs/sdm-assets/assets/config.toml, libs/sdm-assets/assets/log4rs.yml, libs/sdm-assets/assets/settings.toml, libs/sdm-assets/src/configurator.rs, libs/sdm-launchpad/src/bus.rs, libs/sdm-launchpad/src/resources/images/l1_tor.rs, libs/sdm-launchpad/src/resources/images/l3_miner.rs, libs/sdm-launchpad/src/resources/images/l5_xmrig.rs, ui/backend/tauri.conf.json
Description
---
Completed wiring of mining SHA3 and RandomX mining threads into the backend cntainers as this was not implemented fully.
**Note:** Setting the number of XMRig threads has no effect at this time; it may start to work when the new XMRig Docker image is generated as this default user config file will have been removed:
The Docker console screen capture below illustrates that XMRig are started with the correct parameters, but that it has no effect.
```
/ $ top
Mem: 12756268K used, 19955696K free, 37196K shrd, 1184488K buff, 5864140K cached
CPU:  99% usr   0% sys   0% nic   0% idle   0% io   0% irq   0% sirq
Load average: 15.81 18.38 16.62 22/1051 65
PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
1     0 tari     S    2408m   7%   7  56% /usr/local/bin/xmrig …
```
=> feat: add mining threads user control
